---
windows_before_install_tasks : &windows_before_install_tasks
      before_install:
          - python --version
          # - choco install python
          - python -m pip install --upgrade pip
          - pip install --upgrade pytest
          - pip install codecov
          - pip install virtualenv
          - virtualenv $HOME/venv
          - source $HOME/venv/Scripts/activate
windows_install_tasks : &windows_install_tasks
      install:
        - pip install -U pip
        - pip install -U pytest
        - pip install codecov
        - pip install -r requirements.txt

matrix:
  fast_finish: true
  include:

    # - name: "Python 3.7 on bionic"
    #   dist: bionic
    #   language: python
    #   python: 3.7
    #   before_install:
    #     - pip3 install virtualenv
    #     - virtualenv -p $(which python3) ~venvpy3
    #     - source ~venvpy3/bin/activate
    #   install:
    #     - pip3 install -U pip
    #     - pip3 install -U pytest
    #     - pip3 install codecov
    #     - pip install -r requirements.txt
    #   script:
    #     - set -x
    #     - python3 --version
    #     - python2 --version
    #     - python --version
    #     - pip3 --version
    #     - pip2 --version
    #     - pip --version
    #     - pip list
    #     - whoami
    #     - pwd
    #   after_success:
    #     - deactivate
    #
    # - name: "Python 2.7 on xenial"
    #   dist: xenial
    #   language: python
    #   python: 2.7
    #   before_install:
    #     - pip install virtualenv
    #     - virtualenv -p $(which python2) ~venvpy2
    #     - source ~venvpy2/bin/activate
    #   install:
    #     - pip install -r requirements.txt
    #   script:
    #     - set -x
    #     - python2 --version
    #     - python --version
    #     - pip2 --version
    #     - pip --version
    #     - pip list
    #     - whoami
    #     - pwd
    #
    #   after_success:
    #     - deactivate
    #
    # - name: "Python 2.7.17 on macOS xcode10.2"
    #   os: osx
    #   osx_image: xcode10.2  # travis-ci-macos10.14-xcode10.2-19-1573099784 (via amqp)
    #   language: shell
    #   before_install:
    #     - pip install virtualenv
    #     - virtualenv -p $(which python2) ~venvpy2
    #     - source ~venvpy2/bin/activate
    #   install:
    #     - pip install -r requirements.txt
    #   script:
    #     - set -x
    #     - python3 --version
    #     - python2 --version
    #     - python --version
    #     - pip3 --version
    #     - pip2 --version
    #     - pip --version
    #     - pip list
    #     - whoami
    #     - pwd
    #   after_success:
    #     - deactivate
    #
    # - name: "Python 3.7.5 on macOS xcode10.2"
    #   os: osx
    #   osx_image: xcode10.2  # travis-ci-macos10.14-xcode10.2-19-1573099784 (via amqp)
    #   language: shell
    #   before_install:
    #     - pip3 install virtualenv
    #     - virtualenv -p $(which python3) ~venvpy3
    #     - source ~venvpy3/bin/activate
    #   install:
    #     - pip3 install -U pip
    #     - pip3 install -U pytest
    #     - pip3 install codecov
    #     - pip install -r requirements.txt
    #   script:
    #     - set -x
    #     - python3 --version
    #     - python2 --version
    #     - python --version
    #     - pip3 --version
    #     - pip2 --version
    #     - pip --version
    #     - pip list
    #     - whoami
    #     - pwd
    #   after_success:
    #     - deactivate
    #
    # - name: "Python 3.7.5 on macOS xcode9.4 "
    #   os: osx
    #   osx_image: xcode9.4  # travis-ci-macos10.13-xcode9.4.1-19-1576204381
    #   language: shell  # 'language: python' is an error on Travis CI macOS
    #   before_install:
    #     - pip3 install virtualenv
    #     - virtualenv -p $(which python3) ~venvpy3
    #     - source ~venvpy3/bin/activate
    #   install:
    #     - pip3 install -U pip
    #     - pip3 install -U pytest
    #     - pip3 install codecov
    #     - pip install -r requirements.txt
    #   script:
    #     - set -x
    #     - python3 --version
    #     - python2 --version
    #     - python --version
    #     - pip3 --version
    #     - pip2 --version
    #     - pip --version
    #     - pip list
    #     - whoami
    #     - pwd
    #   after_success:
    #     - deactivate

    - name: "Python 3.8 on Windows"
      os: windows           # travis-ci-windows-1803-containers-1569974367-710c8b1d
      language: shell
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
      # <<: *windows_before_install_tasks
      before_install:
        - choco install python --version 3.8.1
        - python -m pip install --upgrade pip
        - pip install --upgrade pytest
        - pip install codecov
      <<: *windows_before_install_tasks
        # - pip install virtualenv
        # - virtualenv $HOME/venv
        # - source $HOME/venv/Scripts/activate
      <<: *windows_install_tasks
      script:
        - pip list
      after_success:
        - deactivate

    - name: "Python 3.7 on Windows"
      os: windows
      language: shell
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      before_install:
        - choco install python --version 3.7.3
        - python -m pip install virtualenv
        - virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate
      # <<: *windows_before_install_tasks
      <<: *windows_install_tasks
      script:
        - pip list
      after_success:
        - deactivate
