---
notifications:
  slack:
    on_failure: always
    
fleet_script_tasks : &fleet_script_tasks
      script:
        - python --version
fleet_install_tasks : &fleet_install_tasks
      install:
        - pip install -r requirements.txt

matrix:
  fast_finish: true
  include:

    - name: "Python 3.7 on focal"
      dist: focal 
      language: python # Python 3.6.10 by default
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
      <<: *fleet_install_tasks
      <<: *fleet_script_tasks
      after_success:
        - deactivate

    - name: "Python 3.7 on bionic"
      dist: bionic
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
      <<: *fleet_install_tasks
      <<: *fleet_script_tasks
      after_success:
        - deactivate

    - name: "Python 2.7 on xenial"
      dist: xenial
      language: python
      python: 2.7
      before_install:
        - pip install virtualenv
        - virtualenv -p $(which python2) ~venvpy2
        - source ~venvpy2/bin/activate
      <<: *fleet_install_tasks
      <<: *fleet_script_tasks
      after_success:
        - deactivate

    - name: "Python 2.7 on trusty"
      dist: trusty
      language: python
      python: 2.7
      before_install:
        - pip install virtualenv
        - virtualenv -p $(which python2) ~venvpy2
        - source ~venvpy2/bin/activate
      <<: *fleet_install_tasks
      <<: *fleet_script_tasks
      after_success:
        - deactivate        

    - name: "Python 2.7 on precise"
      dist: precise
      language: python
      python: 2.7
      before_install:
        - pip install virtualenv
        - virtualenv -p $(which python2) ~venvpy2
        - source ~venvpy2/bin/activate
      <<: *fleet_install_tasks
      <<: *fleet_script_tasks
      after_success:
        - deactivate            