---
notifications:
  slack:
    on_failure: always
    
fleet_script_tasks : &fleet_script_tasks
      script:
        - python --version
        - pip list
fleet_install_tasks : &fleet_install_tasks
      install:
        - pip install -U pip
        - pip install -U pytest
        - pip install codecov
        - pip install -r requirements.txt

matrix:
  fast_finish: true
  include:

    - name: "Python 3.7.5 on macOS 10.15.5 osx xcode12u"
      os: osx
      osx_image: 
        - xcode12u
      addons:
        homebrew:
          casks:
          - vagrant
          packages:
          - beanstalk
          update: true
      language: shell
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - python --version
        - pip install -r requirements.txt
      script:
        - brew list --versions
        - vagrant version    
      after_success:
        # - brew cask uninstall multipass
        - deactivate
        
    - name: "Python 2.7.17 on macOS xcode10.2"
      os: osx
      osx_image: xcode10.2
      language: shell
      before_install:
        - pip install virtualenv
        - virtualenv -p $(which python2) ~venvpy2
        - source ~venvpy2/bin/activate
      <<: *fleet_install_tasks
      <<: *fleet_script_tasks
      after_success:
        - deactivate

    - name: "Python 3.7.5 on macOS xcode10.2"
      os: osx
      osx_image: xcode10.2
      language: shell
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
      <<: *fleet_install_tasks
      <<: *fleet_script_tasks
      after_success:
        - deactivate

    - name: "Python 3.7.5 on macOS xcode9.4 "
      os: osx
      osx_image: xcode9.4
      language: shell
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
      <<: *fleet_install_tasks
      <<: *fleet_script_tasks
      after_success:
        - deactivate
